CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  dni TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL DEFAULT 'Usuario RutaYa',
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS incident_reports (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  route_code TEXT NOT NULL,
  incident_type TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
